name: 'Claude Code PR Review'
description: 'Composite action for automated PR review using Claude Code with AWS Bedrock'
author: 'Anthropic'
branding:
  icon: 'check-circle'
  color: 'orange'

inputs:
  custom_review_instructions:
    description: 'Custom review instructions to append to the base prompt'
    required: false
    default: ''
  prompt:
    description: 'Optional prompt to use for the review. If "prompt_file" is also set, that will be used instead.'
    required: false
    default: ''
  prompt_file:
    description: 'Optional file that contains the prompt to use for the review. This takes priority over "prompt".'
    required: false
    default: ''
  allowed_tools:
    description: 'Comma-separated list of tools to allow during the review'
    required: false
    default: ''
  disallowed_tools:
    description: 'Comma-separated list of tools to disallow during the review'
    required: false
    default: ''
  trigger_phrase:
    description: 'The trigger phrase to look for in comments, issue body, or pull request body'
    required: false
    default: '@claude'

runs:
  using: 'composite'
  steps:
  - name: Get PR info for fork support
    if: github.event.issue.pull_request
    id: pr-info
    shell: bash
    env:
      GH_TOKEN: ${{ github.token }}
    run: |
      PR_DATA=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
      echo "pr_head_owner=$(echo "$PR_DATA" | jq -r '.head.repo.owner.login')" >> $GITHUB_OUTPUT
      echo "pr_head_repo=$(echo "$PR_DATA" | jq -r '.head.repo.name')" >> $GITHUB_OUTPUT
      echo "pr_head_ref=$(echo "$PR_DATA" | jq -r '.head.ref')" >> $GITHUB_OUTPUT
      echo "is_fork=$(echo "$PR_DATA" | jq -r '.head.repo.fork')" >> $GITHUB_OUTPUT

  - name: Checkout code
    uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    with:
      repository: ${{ github.event.issue.pull_request && steps.pr-info.outputs.is_fork == 'true' && format('{0}/{1}', steps.pr-info.outputs.pr_head_owner, steps.pr-info.outputs.pr_head_repo) || github.event.pull_request.head.repo.full_name || github.repository }}
      ref: ${{ github.event.issue.pull_request && steps.pr-info.outputs.pr_head_ref || github.event.pull_request.head.ref || github.ref }}
      fetch-depth: 0

  - name: Copy Claude config to home directory
    shell: bash
    run: |
      set -e

      if [ -d "${GITHUB_ACTION_PATH}/.claude" ]; then
        echo "Copying Claude config from ${GITHUB_ACTION_PATH}/.claude to ~/.claude"
        cp -r "${GITHUB_ACTION_PATH}/.claude" ~/.claude
        ls -la ~/.claude/agents
        echo "Claude config copied successfully"
      else
        echo "No .claude directory found at ${GITHUB_ACTION_PATH}/.claude - skipping agent setup"
        exit 1
      fi

  - name: Create Claude Prompt
    id: claude_prompt
    shell: bash
    run: |
      set -euo pipefail

      # Write specific inputs to files to avoid escaping issues with shell arguments
      if [ -n "${{ inputs.prompt }}" ]; then
        cat > /tmp/inputs_prompt <<'EOF'
      ${{ inputs.prompt }}
      EOF
      fi
      if [ -n "${{ inputs.custom_review_instructions }}" ]; then
        cat > /tmp/inputs_custom_review_instructions <<'EOF'
      ${{ inputs.custom_review_instructions }}
      EOF
      fi

      # Render prompt and store it in /tmp/prompt.md
      "${GITHUB_ACTION_PATH}/scripts/create-prompt.sh" \
        "${GITHUB_WORKSPACE}" \
        "${GITHUB_ACTION_PATH}" \
        "${{ inputs.prompt_file }}" \
        "/tmp/inputs_prompt" \
        "/tmp/inputs_custom_review_instructions" \
        "/tmp/prompt.md"

      # Write the final prompt to GitHub Outputs using the multi-line syntax
      {
        echo 'prompt<<EOF'
        cat /tmp/prompt.md
        echo EOF
      } >> $GITHUB_OUTPUT

  - name: Get diff
    shell: bash
    env:
      GH_TOKEN: ${{ github.token }}
      PR_NUMBER: "${{ github.event.issue.number || github.event.pull_request.number }}"
      GH_REPO: ${{ github.repository }}
    run: ${GITHUB_ACTION_PATH}/scripts/diff.sh

  - name: Hide Previous Reviews
    shell: bash
    if: |
      (github.event_name == 'issue_comment' && github.event.comment.body == '@claude') || 
      (github.event_name == 'pull_request_review' && github.event.review.body == '@claude')
    env:
      GH_TOKEN: ${{ github.token }}
      PR_NUMBER: "${{ github.event.issue.number || github.event.pull_request.number }}"
      GH_REPO: ${{ github.repository }}
    run: ${GITHUB_ACTION_PATH}/scripts/hide-previous-reviews.sh

  - name: Set up Python
    uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
    with:
      python-version: '3.11'

  - name: Install uv
    shell: bash
    run: |
      python -m pip install --upgrade pip
      python -m pip install uv==0.6.11
      uv --version

  - name: Configure AWS Credentials (OIDC)
    uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
    with:
      role-to-assume: arn:aws:iam::340752820498:role/auth0-bedrock-github-actions-pr-analyzer
      role-session-name: bedrock-pr-analyzer
      aws-region: us-east-1

  - name: Trigger Claude Code
    uses: anthropics/claude-code-action@9db20ef677c726762b864933147219a688175107  # Claude Code 2.0.46
    with:
      use_bedrock: 'true'
      track_progress: 'true'
      github_token: ${{ github.token }}
      trigger_phrase: ${{ inputs.trigger_phrase }}
      settings: |
        {
          "env": {
            "CLAUDE_CODE_SUBAGENT_MODEL": "global.anthropic.claude-haiku-4-5-20251001-v1:0",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "global.anthropic.claude-haiku-4-5-20251001-v1:0"
          }
        }
      claude_args: |
        --model global.anthropic.claude-sonnet-4-5-20250929-v1:0
        --allowedTools "Bash(git add:*),
          Bash(git commit:*),
          Bash(git push:*),
          Bash(git status:*),
          Bash(git rm:*),
          Bash(git log:*),
          Bash(ls:*),
          Bash(cat diff.txt),
          Edit,
          MultiEdit,
          Glob,
          Grep,
          LS,
          Read,
          Write,
          ${{ inputs.allowed_tools != '' && format('{0},', inputs.allowed_tools) || '' }}
          mcp__github_inline_comment__create_inline_comment"
        --disallowedTools "Bash(git diff:*),
          Bash(git pr diff:*),
          Read(vendor),
          Read(package-lock.json),
          ${{ inputs.disallowed_tools != '' && format('{0},', inputs.disallowed_tools) || '' }}
          Read(dist)"
      prompt: ${{ steps.claude_prompt.outputs.prompt }}
