name: Test Claude Code Review

on:
  issue_comment:
    types: [ created ]
  pull_request_review_comment:
    types: [ created ]
  pull_request_review:
    types: [ submitted ]

jobs:
  claude-review:
    # Use local workflow reference for testing
    uses: ./.github/workflows/claude-code-review.yml
    with:
      # Optional: Add some test-specific instructions
      custom_review_instructions: |
        This is a test of the Claude code review workflow.
        Please provide feedback on:
        - YAML syntax and structure
        - GitHub Actions best practices
        - Any potential security issues
      # Optional: Test disallowed tools
      disallowed_tools: |
        Read(*.md)
